### ISSUE TITLE
Implement a logger in the application

### ISSUE THREAD

**Issue by umairx97** [umairx97/lets-learn-git#4]
I think we need a logging system inside the application which can verbosely log messages such as info, error, 

I'm attaching some of the resources as well  
1. Winston https://www.npmjs.com/package/winston 
2. Log4js https://www.npmjs.com/package/log4js 

Please provide some insights as to which logger we should use and why

**Comment by umairx97** [comment]
@asadikhlas  Did you find any solutions to this? Should we implement winston or log4js ?

**Comment by asadikhlas** [comment]
yes I will implement winston logger in our application because winston is more popular and efficient then log4js

**Comment by umairx97** [comment]
Okay great, Please post this issue in slack channel if you're working on it 

In Progress "Issue Url"

**Comment by asadikhlas** [comment]
okay sure
