### ISSUE TITLE
Connect lets-learn-git with Zenhub or Basecamp.

### ISSUE THREAD

**Issue by xamQrexii** [umairx97/lets-learn-git#6]
It's my suggestion for this project with Zenhub or Basecamp. It will be super easy to track all the activities on each stage of the application.

**Comment by umairx97** [comment]
Great suggestion @xamQrexii  could you share some resources as to which platform is best for us 

Things to look for when scouting platforms 
1. It should have a free plan 
2. should be able to integrate with github

**Comment by xamQrexii** [comment]
I have one suggestion:
We can use Asana for now. It is free and we can easily integrate with GitHub. I am providing the links below:

https://asana.com/apps/github
https://asana.com/pricing

@umairx97 check this and kindly provide some comments on that.

**Comment by xamQrexii** [comment]
We may also use Trello, its providing GitHub integration.

Link: https://blog.trello.com/github-and-trello-integrate-your-commits

@umairx97 kindly check it.

**Comment by umairx97** [comment]
Thanks @xamqrexii, I'll review these tomorrow

**Comment by umairx97** [comment]
@AkmalElahi can you please work on this?

**Comment by asadikhlas** [comment]
Integrated github boards
Closing this
