### ISSUE TITLE
Install bot on slack for daily updates

### ISSUE THREAD

**Issue by xamQrexii** [umairx97/lets-learn-git#7]
Suggestion: Kindly install the BOT on slack for daily updates which will ask the following questions:

1. Which task are you working on?
2. What did you do yesterday?
3. What will you do today?

**Comment by xamQrexii** [comment]
@umairx97 kindly check it

**Comment by umairx97** [comment]
@xamQrexii  I have added Standuply bot to our slack workspace do you see it ?

**Comment by xamQrexii** [comment]
I can see it. It will reach to me Monday to Friday  by 1 PM.

**Comment by umairx97** [comment]
Great. Closing this issue
